#!/usr/bin/ansible-playbook
# no local password saved group_var/proxmox.yaml
#./cluster-shutdown-proxmox.yaml -i hosts.yaml --ask-pass -c paramiko
# with password saved in group_var/proxmox.yaml
# ./cluster-shutdown-proxmox.yaml

---
- hosts: proxmox
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python"
  tasks:
    - name: Instant kill vms
      shell: |
        qm list | grep cluster | column -t | awk '{print $1}' | xargs -n1 qm stop
#    - name: Destroy clusters vms
#      shell: |
#        qm list | grep cluster | column -t | awk '{print $1}' | xargs -n1 qm destroy