proxmox:
  hosts:
    proxmox-pve:
      ansible_host: 192.168.0.90
clusters:
  hosts:
    web-cluster:
      proxmox_template_id: 100
      master_cpu_cores: 4
      master_memory_MB: 4096
      master_mac: 00:0C:29:97:3C:36
      kubernetes:
        k8s_install_version: 1.17.2-0
        docker_install_version: 19.03.5
        service_cidr: "10.100.0.0/12"
        #        pod_network: flannel
        pod_network: calico
        schedule_pods_on_master: no
      kubernetes_components:
      - metrics-server
      - coreos-kube-prometheus
    istio-cluster:
      proxmox_template_id: 100
      master_cpu_cores: 4
      master_memory_MB: 4096
      master_mac: 00:0C:29:97:3C:37
      kubernetes:
        k8s_install_version: 1.17.2-0
        docker_install_version: 19.03.5
        service_cidr: "10.100.0.0/12"
        #        pod_network: flannel
        pod_network: calico
        schedule_pods_on_master: no
      kubernetes_components:
      - metrics-server
      - coreos-kube-prometheus
      - istio-service-mesh
nodepools:
  web-cluster-std-pool:
    count: 4
    proxmox_template_id: 100
    cpu_cores: 4
    memory_MB: 4096
    kubectl_labels:
    - disk=hdd
    - some-other=value
  istio-cluster-std-pool:
    count: 1
    proxmox_template_id: 100
    cpu_cores: 4
    memory_MB: 4096
    kubectl_labels:
    - disk=hdd
    - some-other=value2
#  ------------ generated by script

mastervms:
  hosts:
    web-cluster-master-node:
      ansible_host: 192.168.0.113
      kubernetes:
        k8s_install_version: 1.17.2-0
        docker_install_version: 19.03.5
        service_cidr: 10.100.0.0/12
        pod_network: calico
        schedule_pods_on_master: no
    istio-cluster-master-node:
      ansible_host: 192.168.0.115
      kubernetes:
        k8s_install_version: 1.17.2-0
        docker_install_version: 19.03.5
        service_cidr: 10.100.0.0/12
        pod_network: calico
        schedule_pods_on_master: no
workervms:
  hosts:
    web-cluster-std-pool-worker-node-103:
      ansible_host: 192.168.0.116
      kubectl_labels: 'disk=hdd some-other=value '
      kubernetes:
        k8s_install_version: 1.17.2-0
        docker_install_version: 19.03.5
    web-cluster-std-pool-worker-node-104:
      ansible_host: 192.168.0.117
      kubectl_labels: 'disk=hdd some-other=value '
      kubernetes:
        k8s_install_version: 1.17.2-0
        docker_install_version: 19.03.5
    web-cluster-std-pool-worker-node-105:
      ansible_host: 192.168.0.118
      kubectl_labels: 'disk=hdd some-other=value '
      kubernetes:
        k8s_install_version: 1.17.2-0
        docker_install_version: 19.03.5
    web-cluster-std-pool-worker-node-106:
      ansible_host: 192.168.0.119
      kubectl_labels: 'disk=hdd some-other=value '
      kubernetes:
        k8s_install_version: 1.17.2-0
        docker_install_version: 19.03.5
    istio-cluster-std-pool-worker-node-107:
      ansible_host: 192.168.0.120
      kubectl_labels: 'disk=hdd some-other=value2 '
      kubernetes:
        k8s_install_version: 1.17.2-0
        docker_install_version: 19.03.5
