mastervms:
  hosts:
    web-cluster-master-node:
      ansible_host: 192.168.0.100
      kubernetes:
        k8s_install_version: 1.22.5
        container_runtimes_interface: docker
        cri_install_version: 20.10.12
        service_cidr: 10.100.0.0/12
        pod_network: calico
        pod_network_cidr: 10.200.0.0/16
        schedule_pods_on_master: no
workervms:
  hosts:
    web-cluster-worker-medium-0:
      ansible_host: 192.168.0.102
      kubernetes:
        k8s_install_version: 1.22.5
        container_runtimes_interface: docker
        cri_install_version: 20.10.12
    web-cluster-worker-medium-1:
      ansible_host: 192.168.0.103
      kubernetes:
        k8s_install_version: 1.22.5
        container_runtimes_interface: docker
        cri_install_version: 20.10.12
