#!/usr/bin/ansible-playbook
#    use the following command and pass the VM password when prompted if no group_var clustervms.yaml present
#./install-master.yaml --ask-pass -c paramiko
---
- hosts: master
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python"
  roles:
  - { role: kubernetes/master }