#!/usr/bin/ansible-playbook
#    use the following command and pass the VM root password when prompted
#  if no group_var clustervms.yaml present with ansible_ssh_pass:
#./install-nodes-and-join.yaml --ask-pass -c paramiko

- hosts: master
  become: no
  tasks:
    - name: Generate join token in {{ inventory_hostname }}
      shell: |
        echo "join_line: $(kubeadm token create --print-join-command)" >  /tmp/{{ inventory_hostname }}-join-line.yaml
    - name: Copy file with join command
      fetch:
        src: "/tmp/{{ inventory_hostname }}-join-line.yaml"
        dest: "generated_resources/{{ inventory_hostname }}-join-line.yaml"
        flat: yes

- hosts: node
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python"
  roles:
    - { role: kubernetes/node }




