#!/bin/env ansible-playbook
#    use the following command and pass the VM password when prompted
#./install-after-kubectl-updates.yaml --ask-pass -c paramiko

- hosts: master
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python"
  tasks:
    - name: Add kubectl node labels
      ignore_errors: yes
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"
      command: "kubectl label nodes {{  hostvars[item].inventory_hostname }} {{ hostvars[item].kubectl_labels }}"
      with_items:
        - "{{ groups['clustervms'] }}"

    - name: Label nodes as workers
      ignore_errors: yes
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"

      command: "kubectl label nodes {{  hostvars[item].inventory_hostname }} node-role.kubernetes.io/worker=worker"
      with_items:
        - "{{ groups['node'] }}"

