#!/usr/bin/env ansible-playbook
---
- hosts: k8s-node
  become: yes
  gather_facts: no
  roles:
    - { role: kubernetes/node }

- hosts: k8s-master
  become: yes
  tasks:
    - name: Optional Label nodes as workers
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"
      shell: "kubectl label node {{ item[1] }} node-role.kubernetes.io/worker=worker"
      ignore_errors: yes
      with_indexed_items:
        - "{{ groups['k8s-node'] }}"