---
- name: Add Kubernetes repository
  when: ansible_distribution == "CentOS"
  yum_repository:
    name: Kubernetes
    description: Kubernetes Repository
    file: kubernetes
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: no

- name: Uninstall kubelet kubeadm kubectl
  ignore_errors: yes
  package:
    name: ['kubelet', 'kubeadm', 'kubectl']
    state: absent

- name: Install kubernetes packages
  package:
    name: ['kubelet-{{ hostvars[inventory_hostname].kubernetes.k8s_install_version }}', 'kubeadm-{{ hostvars[inventory_hostname].kubernetes.k8s_install_version  }}', 'kubectl-{{ hostvars[inventory_hostname].kubernetes.k8s_install_version }}', 'nfs-utils']
    update_cache: yes
    state: present

- name: Disable SELinux
  ignore_errors: yes
  selinux:
    state: disabled

- name: ERROR Swap running with swap on is not supported
  shell: "swapoff -a"

- name: Remove fstab swap
  mount:
    path: swap
    fstype: swap
    opts: noatime
    state: absent

- name: CentOS7 have issues with traffic fix conf file
  file:
    path: "/etc/sysctl.d/k8s.conf"
    state: touch

- name: Fix issues with traffic being routed incorrectly due to iptables being bypassed
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: "{{ item }}"
    state: present
  with_items:
    - "net.bridge.bridge-nf-call-ip6tables = 1"
    - "net.bridge.bridge-nf-call-iptables = 1"
- shell: "sysctl --system"

- name: Reload kubelet daemon
  systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes