---
- name: Add Kubernetes repository CentOS
  when: ansible_distribution == "CentOS"
  yum_repository:
    name: Kubernetes
    description: Kubernetes Repository
    file: kubernetes
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: no


- name: Add Kubernetes Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repository Ubuntu
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present



- name: Uninstall kubelet kubeadm kubectl
  ignore_errors: yes
  package:
    name: ['kubelet', 'kubeadm', 'kubectl']
    state: absent

- name: Install kubernetes packages CentOS
  when: ansible_distribution == "CentOS"
  # GET VERSIONS using yum list available kubelet
  package:
    name: ['kubelet-{{ hostvars[inventory_hostname].kubernetes.k8s_install_version }}-0', 'kubeadm-{{ hostvars[inventory_hostname].kubernetes.k8s_install_version }}-0', 'kubectl-{{ hostvars[inventory_hostname].kubernetes.k8s_install_version }}-0', 'nfs-utils']
    update_cache: yes
    state: present

- name: Install kubernetes packages Ubuntu
  when: ansible_distribution == "Ubuntu"
  # GET VERSIONS for ubuntu apt-cache policy kubelet
  package:
    name: ['kubelet={{ hostvars[inventory_hostname].kubernetes.k8s_install_version }}-00', 'kubeadm={{ hostvars[inventory_hostname].kubernetes.k8s_install_version }}-00', 'kubectl={{ hostvars[inventory_hostname].kubernetes.k8s_install_version }}-00', 'nfs-kernel-server']
    update_cache: yes
    state: present

- name: Disable SELinux
  ignore_errors: yes
  selinux:
    state: disabled

- name: Disable swap. Running with swap on is not supported
  shell: "swapoff -a"


- name: Disable SWAP permanently
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Reload kubelet daemon
  systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes