---
- name: Get local k8s installation version
  shell: "kubelet --version | awk ' { print $2 }'"
  register: get_kubelet_version
- name: Set fact k8s_local_version
  set_fact:
    k8s_local_version: "{{ get_kubelet_version.stdout[1:] }}-0"
- name: k8s_local_version
  debug: var=k8s_local_version

- name: Install kube dependencies components if required Ubuntu
  when: k8s_local_version!=hostvars[inventory_hostname].kubernetes.k8s_install_version and ansible_distribution == "Ubuntu"
  include_tasks: install_kube_dependecies_ubuntu.yaml

- name: Install kube dependencies components if required CentOS
  when: k8s_local_version!=hostvars[inventory_hostname].kubernetes.k8s_install_version and ansible_distribution == "CentOS"
  include_tasks: install_kube_dependecies_centos.yaml