---
- name: Get local k8s installation version
  shell: "kubelet --version | awk ' { print $2 }'"
  register: get_kubelet_version
- set_fact:
    k8s_local_version: "{{ get_kubelet_version.stdout[1:] }}-0"

- name: Install kube dependencies components if required
  when: k8s_local_version!=k8s_expected_version
  include_tasks: install_kube_dependecies.yaml