- name: Provision master nodes for each cluster
  include_tasks: provision-master-vms.yaml

- name: Provision worker nodes for each cluster
  include_tasks: provision-node-pool-vms.yaml

# TODO not as efficient , qm list is not reporting stuck VMs
- name: Wait until all vms are running
  shell: echo "result $(qm list | grep cluster | grep -v running | column -t 2>&1)"
  delay: 5
  retries: 10
  register: qm_cluster_vm_status
  until: qm_cluster_vm_status.stdout.find("stopped") == -1
  ignore_errors: yes

# TODO temporary wait for VM to boot up. Improve with other check like a listening state of a socket
- name: Pause the process of extraction IPs until guest vms are booted up
  pause:
    minutes: 3

- name: Extract each VM IP
  include_tasks: extract-vms-ips.yaml