#!/usr/bin/env ansible-playbook

#./optionals/optional-install-configure-local-kubectl.yaml --ask-become-pass
---

- hosts: localhost
  connection: local
  remote_user: root
  gather_facts: no
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python"
  tasks:
    - name: Add Kubernetes repository
      yum_repository:
        name: Kubernetes
        description: Kubernetes Repository
        file: kubernetes
        baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
        enabled: yes
        gpgcheck: no

    - name: Install kubernetes packages
      package:
        name: kubectl
        update_cache: yes
        state: latest

- hosts: localhost
  connection: local
  become: no
  tasks:
    - name: Set kubectl config dir
      file:
        path: "{{ lookup('env','HOME') }}/.kube"
        state: directory

    - name: Override generated config files
      shell: "cp ../generated_resources/config {{ lookup('env','HOME') }}/.kube/config"