---
- name: Stop VMs
  shell: |
    export VM_ID={{ hostvars[item].vm }}
    qm stop $VM_ID
  with_items:
    - "{{ groups['clustervms'] }}"

- name: ReCreate cluster
  shell: |
    export VM_ID={{ hostvars[item].vm }}
    qm destroy $VM_ID --purge true
    qm clone 100 $VM_ID \
    --description "the cloned master-node" \
    --name {{ hostvars[item].inventory_hostname }}
    qm set $VM_ID \
    --net0 virtio,bridge=vmbr0,macaddr={{ hostvars[item].mac }} \
    --memory {{ hostvars[item].memory }} \
    --cores {{ hostvars[item].cores }} \
    --autostart true
    qm set $VM_ID -onboot 1
  with_items:
    - "{{ groups['clustervms'] }}"

- name: Start VMs
  shell: |
    export VM_ID={{ hostvars[item].vm }}
    qm start $VM_ID
  with_items:
    - "{{ groups['clustervms'] }}"
