- name: Provision master nodes for each cluster
  include_tasks: provision-master-vms.yaml

- name: Provision worker nodes for each cluster
  include_tasks: provision-node-pool-vms.yaml

- name: Extract each VM IP
  include_tasks: extract-vms-ips.yaml