- name: Install docker on node
  include_role:
    name: docker

- name: Install kubernetes packages
  include_role:
    name:  kubernetes/packages

- name: disable firewalld
  systemd: name=firewalld enabled=no
- name: stop firewalld
  systemd: name=firewalld state=stopped

- name: Worker join cluster
  include_tasks: join_cluster.yml