---
- name: Include generated kubeadm join line
  include_vars:
    dir: "{{ playbook_dir }}/generated_resources"
    files_matching: generated_vars.yml

- name: Reset Kubernetes master
  shell: "kubeadm reset --force"
  register: reset_cluster
# TODO check if firewall is not a problem anymore
#- name: fixing network communication
#  systemd:
#    name: kubelet
#    state: stopped
#- name: fixing network communication
#  systemd:
#    name: docker
#    state: stopped
#- name: fixing network communication
#  shell: "iptables --flush"
#- name: fixing flannel communication
#  shell: "iptables -tnat --flush"
#- name: fixing network communication
#  shell: "iptables -P FORWARD ACCEPT"
#- name: fixing flannel communication
#  ignore_errors: yes
#  shell: "ip link del docker0"
#- name: fixing network communication
#  systemd:
#    name: docker
#    state: reloaded
#    enabled: yes
#- name: fixing network communication
#  systemd:
#    name: kubelet
#    state: reloaded
#    enabled: yes

- name: execute join command
  shell: "{{ join_line }}"
  register: join_cluster
- debug: var=join_cluster