apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    provider: coreos-kube-prometheus
  name: prometheus-adapter
  namespace: monitoring
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: