---

- name: Reset Kubernetes master
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Init Kubernetes cluster using calico pod network
  when: reset_cluster is succeeded and pod_network=='calico'
  shell: |
    kubeadm init --service-cidr {{ service_cidr }} \
                 --pod-network-cidr {{ calico_pod_network_cidr }} \
                 --apiserver-advertise-address 0.0.0.0 \
                 >  /tmp/kubeadm_init.log


- name: Init Kubernetes cluster using flannel pod networl
  when: reset_cluster is succeeded and pod_network=='flannel'
  shell: |
    kubeadm init --service-cidr {{ service_cidr }} \
                 --pod-network-cidr {{ flannel_pod_network_cidr }} \
                 --apiserver-advertise-address 0.0.0.0 \
                 >  /tmp/kubeadm_init.log

- name: Get calico yaml to update the default 192.168.0.0 cidr
  when: pod_network=='calico'
  get_url:
    url: "{{ calico_version_yaml }}"
    dest: /tmp/calico.yaml
    force: yes

- name: Update config with local defined IP range
  when: pod_network=='calico'
  lineinfile:
    path: /tmp/calico.yaml
    regexp: '^              value: "192.168.0.0/16"'
    line: '              value: "{{ calico_pod_network_cidr }}"'

- name: Apply Calico yaml
  when: pod_network=='calico'
  command: "kubectl apply -f /tmp/calico.yaml"
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  register: calico_yaml
- debug: var=calico_yaml.stdout_lines

- name: Bridged IPv4 traffic to iptables’ chains. This is a requirement for some CNI plugins to work
  when: pod_network=='flannel'
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

- name: Install Flannel network kdd
  when: pod_network=='flannel'
  command: "kubectl apply -f {{ flannel_remote_yaml }}"
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  register: flannel_out
- debug: var=flannel_out.stdout_lines

- name: Remove taint from master to schedule pods on it
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  command: "kubectl taint nodes --all node-role.kubernetes.io/master-"
  register: schedule_pods_master
- debug: var=schedule_pods_master.stdout_lines




