---
- include_role:
    name: hosts_entries

- include_role:
    name:  kubernetes/packages

- include_role:
    name: docker

- name: disable firewalld
  systemd: name=firewalld enabled=no
- name: stop firewalld
  systemd: name=firewalld state=stopped

- name: Get local k8s installation version
  shell: echo "no_apiserver_container$(docker ps | grep k8s_kube-apiserver)"
  register: get_kube_apiserver_docker
- name: get_kube_apiserver_docker
  debug: var=get_kube_apiserver_docker

- name: Initialize kubeadm if not already initialized
  when: get_kube_apiserver_docker.stdout == "no_apiserver_container"
  include_tasks: kubeadm_init.yaml

- name: Add kube config on root master for kubectl dirrect access
  lineinfile:
    path: "/root/.bashrc"
    line: "export KUBECONFIG=/etc/kubernetes/admin.conf"
    state: present






