---
- include_role:
    name: hosts_entries

- include_role:
    name:  kubernetes/packages

- include_role:
    name: docker

- name: disable firewalld
  systemd: name=firewalld enabled=no
- name: stop firewalld
  systemd: name=firewalld state=stopped

- name: Initialize kubeadm
  include_tasks: kubeadm_init.yml

- name: Add kube config on root master for kubectl dirrect access
  lineinfile:
    path: "/root/.bashrc"
    line: "export KUBECONFIG=/etc/kubernetes/admin.conf"
    state: present

- name: Copy kubeadm init logs to local env for extraction
  fetch:
    src: /tmp/kubeadm_init.log
    dest: generated_resources/kubeadm_init.log
    flat: yes

- name: Copy kubectl admin config
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: generated_resources/config
    flat: yes





