  - name: Make sure docker is stoped
    systemd:
      name: docker
      state: stopped
    ignore_errors: yes

  - name: Uninstall docker engine old
    yum:
      name: [
        'docker',
        'docker-client',
        'docker-client-latest',
        'docker-common',
        'docker-latest',
        'docker-latest-logrotate',
        'docker-logrotate',
        'docker-selinux',
        'docker-engine-selinux',
        'docker-ce-cli',
        'docker-engine']
      state: absent

  - name: Install docker utils
    yum:
      name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
      state: present

  - name: Add docker repository
    shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

  - name: Install docker engine latest option (RHEL/CentOS)
    when: hostvars[inventory_hostname].kubernetes.docker_install_version=='latest'
    yum:
      name: "docker-ce-{{ hostvars[inventory_hostname].kubernetes.docker_install_version.replace('-', '.') }}-3.el7"
      state: present

  - name: "Install docker engine specific version docker-ce-{{ hostvars[inventory_hostname].kubernetes.docker_install_version }}-3.el7 (RHEL/CentOS)"
    when: hostvars[inventory_hostname].kubernetes.docker_install_version!='latest'
    yum:
      name: "docker-ce-{{ hostvars[inventory_hostname].kubernetes.docker_install_version }}-3.el7"
      state: present

  - name: Reload service docker
    systemd:
      name: docker
      state: reloaded
      enabled: yes