---
- name: Get local docker installation
  shell: "docker version | grep -A 2 Server | awk 'FNR == 3 { print $2 }'"
  register: get_docker_version
- set_fact:
    docker_local_version: "{{ get_docker_version.stdout }}"
- debug: var=calico_kube_controllers.stdout

- name: Install Docker container specific version
  when: docker_local_version!=hostvars[inventory_hostname].kubernetes.cri_install_version
  include_tasks: install_docker.yml


