---
- debug: var=inventory_hostname

- name: Set instace hostname as defined in the hosts.yaml
  hostname:
    name: "{{ inventory_hostname }}"

- name: Init list
  set_fact:
    host_cluster_entries: []

- name: Get hosts entries for all vms
  set_fact:
    host_cluster_entries: "{{ host_cluster_entries }} + [ '{{ hostvars[item].ansible_host }} {{ item }}' ]"
  with_items:
    - "{{ groups['mastervms'] }}"
    - "{{ groups['workervms'] }}"
- debug: var=host_cluster_entries

- name: Update entries in etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    state: present
  with_items:
  - "{{ host_cluster_entries }}"