- debug: var=inventory_hostname

- name: Set instace hostname as defined in the hosts.yaml
  hostname:
    name: "{{ inventory_hostname }}"

- name: Init list
  set_fact:
    host_cluster_entries: []

- name: Update entries in etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  with_items:
  - "{{ groups['all'] }}"
