---

- name: Init ip list
  set_fact:
    ip_entries: []

- name: Append k8s master
  set_fact:
    ip_entries: "{{ ip_entries }} + [ '{{ item }} k8s-master' ]"
  with_items:
    - "{{ groups['k8s-master'] }}"

- name: Append k8s Nodes
  set_fact:
    ip_entries: "{{ ip_entries }} + [ '{{ item[1] }} k8s-node-{{ item[1][item[1].rfind('.')+1:]}}' ] "
  with_indexed_items:
  - "{{ groups['k8s-node'] }}"


- name: Add entries to hosts file
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    state: present
  with_items:
  - "{{ ip_entries }}"